 language: c++
os: linux 
dist: bionic
sudo: required

matrix:
  include:
    - compiler: gcc
      env: CMAKE_CXX_STANDARD=14 BUILD_TYPE=Release
    - compiler: clang
      env: CMAKE_CXX_STANDARD=14 BUILD_TYPE=Release

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++
  - sudo update-alternatives --install /usr/bin/g++ g++ 90
  - wget https://cmake.org/files/v3.9/cmake-3.9.2-Linux-x86_64.sh
  - sudo sh cmake-3.9.2-Linux-x86_64.sh -- --skip-license --prefix=/usr

script:
  - mkdir build ; cd build
  - cmake -DBUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=../install ..
  - cmake --build . --config $BUILD_TYPE
  - cmake --build . --target install