language: cpp
sudo: required

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test
    packages: &base_packages
      - libffi-dev
      - libstdc++6
      - binutils-gold
      # Provides a backtrace if the unittests crash
      - gdb

matrix:
  include:

    # GCC 8, C++14, libstdc++, RelWithDebInfo
    - os: linux
      dist: xenial
      compiler: g++-8
      env:
        - VARIANT=RelWithDebInfo
        - TOOLSET=gcc
        - CCOMPILER=gcc-8
        - CXXCOMPILER=g++-8
        - CXXSTD=14
      addons:
        apt:
          packages:
            - g++-8
            - *base_packages
          sources:
            - *base_sources

install:
  #- cd ..
  - mkdir tmp ; cd tmp

  # Install openssl
  - sudo add-apt-repository ppa:carsten-uppenbrink-net/openssl -y
  - sudo apt-get update
  - sudo apt-get install libssl-dev openssl -y
  - sudo ldconfig

  # Install boost
  - wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
  - tar -xzf boost_1_72_0.tar.gz
  - cd boost_1_72_0
  - ./bootstrap.sh
  - travis_wait 30 sudo ./b2 -a toolset=$TOOLSET cxxflags="-fPIC" -j3 install
  - cd ..
  - sudo ldconfig

  # Install cmake
  - wget https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.sh
  - travis_wait 30 sudo sh cmake-3.10.0-Linux-x86_64.sh -- --skip-license --prefix=/usr

script:
  - cd ..
  - mkdir build ; cd build
  - sudo cmake .. -DCMAKE_BUILD_TYPE=$VARIANT -DCMAKE_C_COMPILER=$CCOMPILER -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DBUILD_TESTS=ON -DENABLE_LOGGING=ON -DBUILD_WITH_ASAN=ON -DBUILD_WITH_UBSAN=ON -DBUILD_WITH_VALGRIND=ON -DIS_CI_BUILD=ON
  - sudo cmake --build . --config $VARIANT -- -j 3
  - sudo ctest -j1