version: 1.0.{build}-{branch}

shallow_clone: true

platform:
  - x64

branches:
  only:
    - master
    - dev

configuration:
  - Release

environment:
  OPENSSL_ROOT_DIR: C:\OpenSSL-v111-Win64\bin
  BOOST_ROOT: C:\Libraries\boost_1_71_0
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOOLSET: msvc-14.2

install:
  - md build
  - cd build
  - cmake -DOPENSSL_INCLUDE_DIR=C:\OpenSSL-v111-Win64\include -DCMAKE_BUILD_TYPE=$%CONFIGURATION% -DBUILD_TESTS=ON -DENABLE_LOGGING=ON -DIS_CI_BUILD=ON -G "Visual Studio 16 2019" ..
  - cmake --build . --config %CONFIGURATION%

build: off
