function(set_definitions TARGET SANTIZER_STRING)
    if(SUPPORT_SSL)
        set(COMPILE_DEFINITIONS ${COMPILE_DEFINITIONS} RADRPC_SSL_SUPPORT)
    endif()
    if(LOGGING)
        set(COMPILE_DEFINITIONS ${COMPILE_DEFINITIONS} RADRPC_LOGGING)
        set(COMPILE_DEFINITIONS ${COMPILE_DEFINITIONS} RADRPC_LOGGING_THREADID)
    endif()
    if(NOT "${SANTIZER_STRING}" STREQUAL "")
        set(COMPILE_DEFINITIONS ${COMPILE_DEFINITIONS} SANITIZER_ACTIVE)
    endif()
    # Workaround for UndefinedBehaviorSanitizer, got no __has_feature (just used for tests)
    if("${SANTIZER_STRING}" STREQUAL "address")
        set(COMPILE_DEFINITIONS ${COMPILE_DEFINITIONS} ASAN)
    endif()
    if("${SANTIZER_STRING}" STREQUAL "undefined")
        set(COMPILE_DEFINITIONS ${COMPILE_DEFINITIONS} UBSAN)
    endif()
    if("${SANTIZER_STRING}" STREQUAL "memory")
        set(COMPILE_DEFINITIONS ${COMPILE_DEFINITIONS} MSAN)
    endif()
    if("${SANTIZER_STRING}" STREQUAL "thread")
        set(COMPILE_DEFINITIONS ${COMPILE_DEFINITIONS} TSAN)
    endif()
    target_compile_definitions(${TARGET} PRIVATE ${COMPILE_DEFINITIONS})
endfunction()