set(SANTIZERS "")
if(BIN_ASAN)
    set(SANTIZERS ${SANTIZERS} address)
endif()
if(BIN_UBSAN)
    set(SANTIZERS ${SANTIZERS} undefined)
endif()
if(BIN_TSAN)
    set(SANTIZERS ${SANTIZERS} thread)
endif()
if(BIN_MSAN AND INSTRUMENTED_FOUND)
    set(SANTIZERS ${SANTIZERS} memory)
endif()