set(SANTIZERS "")
if(BUILD_WITH_ASAN)
    set(SANTIZERS ${SANTIZERS} address)
endif()
if(BUILD_WITH_UBSAN)
    set(SANTIZERS ${SANTIZERS} undefined)
endif()
if(BUILD_WITH_TSAN)
    set(SANTIZERS ${SANTIZERS} thread)
endif()
if(BUILD_WITH_MSAN AND INSTRUMENTED_FOUND)
    set(SANTIZERS ${SANTIZERS} memory)
endif()